version: 1

formatters:
  simple:
    format: "%(asctime)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  file:
    class: logging.handlers.TimedRotatingFileHandler
    when: midnight
    backupCount: 5
    level: DEBUG
    formatter: simple
    filename: game.log

loggers:
  __main__:
    level: DEBUG
    handlers: [console, file]
    propagate: yes
